# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$fill\
$nodejs\
$python\
$rust\
$docker_context\
$cmd_duration $jobs $time\
$line_break\
$character"""
# Inserts a blank line between shell prompts
add_newline = false

[fill]
symbol = " "

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[](bold red)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
vimcmd_symbol = '[](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
vimcmd_replace_one_symbol = '[](bold purple)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
vimcmd_replace_symbol = '[](bold purple)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
vimcmd_visual_symbol = '[󰒅](bold purple)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = '…/'

[nodejs]
format = "[ $version](bold green)"

[docker_context]
format = " [$symbol$context]($style)"

[time]
disabled = false
use_12hr = true
format = "[$time]($style)"
